project_id = "qyyreinrwjygrmuprlwu"

[functions.facebook-conversions]
verify_jwt = false

[functions.send-follow-up]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.security-monitor]
verify_jwt = false