project_id = "dcfmrqrbsfxvqhihpamd"

[functions.collaborator-upload]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false

[functions.gmail-send]
verify_jwt = false

[functions.gmail-monitor]
verify_jwt = false

[functions.automation-engine]
verify_jwt = false

[functions.notify-partner-lead-progress]
verify_jwt = false
[functions.invite-partner-portal]
verify_jwt = false

[functions.notify-proposal-signed]
verify_jwt = false

