// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyyreinrwjygrmuprlwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5eXJlaW5yd2p5Z3JtdXBybHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDIxNzcsImV4cCI6MjA3MzM3ODE3N30.7rrplC52OsATVwg8olmbp4xBYg_sAuz3hIhEQX02sWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});